name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Set version from release tag
        run: bun pm pkg set version="${{ github.event.release.tag_name }}"

      - name: Build the file
        run: bun run build

      - name: Upload build result to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/lg-remote-control.js
          fail_on_unmatched_files: true
